---
name: App-TimeTracker
version: 0.08
author:
  - 'Thomas Klausner <domm@cpan.org>'
abstract: Track time spend on projects from the commandline
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::Cmd: 0.012
  Class::Accessor: 0.31
  DBD::SQLite: 1.14
  DBIx::Class: 0.08008
  DateTime: 0.41
  DateTime::Format::Strptime: 1.0702
  Exception::Class: 1.23
  File::HomeDir: 0.67
build_requires:
  Test::More: 0
  Test::NoWarnings: 0.084
provides:
  App::TimeTracker:
    file: lib/App/TimeTracker.pm
    version: 0.08
  App::TimeTracker::Command::current:
    file: lib/App/TimeTracker/Command/current.pm
  App::TimeTracker::Command::report:
    file: lib/App/TimeTracker/Command/report.pm
  App::TimeTracker::Command::start:
    file: lib/App/TimeTracker/Command/start.pm
  App::TimeTracker::Command::stop:
    file: lib/App/TimeTracker/Command/stop.pm
  App::TimeTracker::Command::worked:
    file: lib/App/TimeTracker/Command/worked.pm
  App::TimeTracker::Schema:
    file: lib/App/TimeTracker/Schema.pm
  App::TimeTracker::Schema::Project:
    file: lib/App/TimeTracker/Schema/Project.pm
  App::TimeTracker::Schema::Tag:
    file: lib/App/TimeTracker/Schema/Tag.pm
  App::TimeTracker::Schema::Task:
    file: lib/App/TimeTracker/Schema/Task.pm
  App::TimeTracker::Schema::TaskTag:
    file: lib/App/TimeTracker/Schema/TaskTag.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
